# Generated by Django 2.2.1 on 2019-05-10 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('done', models.BooleanField(default=False)),
                ('author_ip', models.CharField(blank=True, max_length=25)),
                ('created_date', models.CharField(default='2019-05-10, 20:10:46', max_length=50)),
                ('done_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
